### PR TITLE
fix error in judging aarch64 interrupts enabled

### PR DESCRIPTION
**Pull request by xuzhuosen**

### CODE REVIEW

**Comment by NathanRoyer** [comment]
The current implementation of `interrupts_enabled` checks that the I & F flags are unset/cleared.
Them being unset corresponds to IRQ/FIQ exceptions being unmasked, i.e. these kinds of interrupts are allowed/enabled.

The changes in this PR makes `interrupts_enabled` check that at least one of these flags is set; if the flags are set, it means that the IRQ/FIQ exceptions are masked: these kinds of interrupts are disabled. So, if we merged this PR, `interrupts_enabled` would check that interrupts are disabled.

Additionally, when I try to boot theseus using this branch of irq_safety, the boot log shows that theseus resolves an invalid pointer. Did it boot successfully on your side?

**Comment by xuzhuosen** [comment]
Your explanation is correct. I'm sorry that I created a wrong PR. 

But I am trying to use  [irq_safety] in other project, where only IRQ was enabled, but FIQ was not enabled. In this case, interrupts_enabled() gives an incorrect result. Maybe change it to daif >> 6 & 0x3 != 0x3 and modify other related content at the same time will meet the demand. But I'm not sure how that will affect theseus.

I have no experience creating PRs, and perhaps I should consider and test them in theseus. Sorry for wasting your time. So what should I need to do next?

**Comment by NathanRoyer** [comment]
The feature you request (the ability to mask/unmask FIQs/IRQs separately) is specific to aarch64, whereas this crate aims to unify the masking of irq-like events across multiple platforms, including x86 where FIQs don't exist in the same form.

Based on this, I don't think that feature should be implement in this crate. Instead, as this code is pretty short, you can surely copy it somewhere else (another crate/repo/project) and make the relevant changes there.

**Comment by xuzhuosen** [comment]
Ok, thanks

**Comment by kevinaboos** [comment]
In #10 we added support for separately enabling/disabling regular and fast interrupts, so that should cover the concerns of this PR.

**Pull request closed without merging**
